//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: xml serialization ([XmlType]/[XmlElement]) enabled
    
// Generated from: xml_proto/string_config.proto
namespace Config
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StringConfig")]
  [global::System.Xml.Serialization.XmlType(TypeName=@"StringConfig")]
  public partial class StringConfig : global::ProtoBuf.IExtensible
  {
    public StringConfig() {}
    
    // TYPE_STRING : key
    private string _key = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"key", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    [global::System.Xml.Serialization.XmlAttribute(@"key")]
        
    public string key
    {
      get { return _key; }
      set { _key = value; }
    }
    // TYPE_MESSAGE.Config.StringCfgLang : lang
    private  global::System.Collections.Generic.List<Config.StringCfgLang> _lang = new global::System.Collections.Generic.List<Config.StringCfgLang>();
    [global::ProtoBuf.ProtoMember(2, Name=@"lang", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.Xml.Serialization.XmlElement(@"lang")]
    
    public global::System.Collections.Generic.List<Config.StringCfgLang> lang
    {
      get { return _lang; }
      set { _lang = value; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StringCfgLang")]
  [global::System.Xml.Serialization.XmlType(TypeName=@"StringCfgLang")]
  public partial class StringCfgLang : global::ProtoBuf.IExtensible
  {
    public StringCfgLang() {}
    
    // TYPE_INT32 : id
    private int _id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    [global::System.Xml.Serialization.XmlAttribute(@"id")]
        
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    // TYPE_STRING : value
    private string _value = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    [global::System.Xml.Serialization.XmlAttribute(@"value")]
        
    public string value
    {
      get { return _value; }
      set { _value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}