//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: xml serialization ([XmlType]/[XmlElement]) enabled
    
// Generated from: sheet_proto/test_sheet.proto
namespace Config
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TestSheet")]
  [global::System.Xml.Serialization.XmlType(TypeName=@"TestSheet")]
  public partial class TestSheet : global::ProtoBuf.IExtensible
  {
    public TestSheet() {}
    
    // TYPE_INT32 : id
    private int _id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    [global::System.Xml.Serialization.XmlAttribute(@"id")]
        
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    // TYPE_STRING : name
    private string _name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    [global::System.Xml.Serialization.XmlAttribute(@"name")]
        
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}