//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: xml serialization ([XmlType]/[XmlElement]) enabled
    
// Generated from: xml_proto/test_config.proto
namespace Config
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TestConfig")]
  [global::System.Xml.Serialization.XmlType(TypeName=@"TestConfig")]
  public partial class TestConfig : global::ProtoBuf.IExtensible
  {
    public TestConfig() {}
    
    // TYPE_INT32 : id
    private int _id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    [global::System.Xml.Serialization.XmlAttribute(@"id")]
        
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    // TYPE_MESSAGE.Config.TestChildData : child
    private  global::System.Collections.Generic.List<Config.TestChildData> _child = new global::System.Collections.Generic.List<Config.TestChildData>();
    [global::ProtoBuf.ProtoMember(2, Name=@"child", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.Xml.Serialization.XmlElement(@"child")]
    
    public global::System.Collections.Generic.List<Config.TestChildData> child
    {
      get { return _child; }
      set { _child = value; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TestChildData")]
  [global::System.Xml.Serialization.XmlType(TypeName=@"TestChildData")]
  public partial class TestChildData : global::ProtoBuf.IExtensible
  {
    public TestChildData() {}
    
    // TYPE_INT32 : id
    private int _id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    [global::System.Xml.Serialization.XmlAttribute(@"id")]
        
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    // TYPE_STRING : names
    private  global::System.Collections.Generic.List<string> _names = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(2, Name=@"names", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.Xml.Serialization.XmlElement(@"names")]
    
    public global::System.Collections.Generic.List<string> names
    {
      get { return _names; }
      set { _names = value; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}